### ISSUE TITLE
Pass primary branch name

### ISSUE THREAD

**Issue by thedavidprice** [openclimatefix/merge-all-contributors#3]
Our repos use `main` instead of `master`. It would be helpful if this either checked for the default GH branch or it was possible to pass the target branch name here: https://github.com/openclimatefix/merge-all-contributors/blob/c40d02f37641c8febced9a309098e96f90243984/index.js#L39

I could take a stab at a PR. Or happy to fork and modify specific to our use.

Most of all, thanks for putting this together!!

**Comment by flowirtz** [comment]
Ah good call, that shouldn't be hardcoded! We haven't gotten around to move our repos to `main` yet.

Very open for a PR, totally happy about either implementation you suggested.
Thanks!!

**Comment by thedavidprice** [comment]
Hi all -- super delayed reply here. I ended up writing our own script for this as our use case ended up diverging a bit. Closing out this issue. Really appreciate your original response and invitation!

**Comment by flowirtz** [comment]
Hey, @thedavidprice, no worries at all. Is this work open-source or do you mind sharing a bit more? Sounds interesting!

**Comment by thedavidprice** [comment]
Sure thing. It's for [RedwoodJS](https://github.com/redwoodjs/redwood). There are three primary repos where people contribute to docs and code. We wanted to display on the primary framework repo README, which is also displayed on our website https://redwoodjs.com/docs/introduction#contributors

Here's the current state of files and code with the corresponding README. You'll recognize some of the code used in the script to merge contributors into one `.rc`. Overall, currently in a bit of a hacky state, but working works at the start, right? 😆
